name: Deploy

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy new version
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Deploy via ssh
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: rm deploy.sh; wget https://raw.githubusercontent.com/0x6D70/chat/main/scripts/deploy.sh; echo ${{ secrets.PASSWORD }} | sudo -S bash ./deploy.sh
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
