name: Deploy

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy new version
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Deploy via ssh
              uses: garygrossgarten/github-action-ssh@release
              with:
                  command: echo ${{ secrets.PASSWORD }} | sudo -S sh ./test.sh
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
